# Generated by Django 5.2.7 on 2025-10-13 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_mangement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('reason', models.CharField(db_index=True, default='manual', max_length=100)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('escalation_level', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_ips', to='site_mangement.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'indexes': [models.Index(fields=['site', 'ip_address'], name='site_mangem_site_id_2f2d94_idx'), models.Index(fields=['site', 'expires_at'], name='site_mangem_site_id_fcea9a_idx')],
                'unique_together': {('site', 'ip_address')},
            },
        ),
    ]
