# Generated by Django 5.2.7 on 2025-10-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_mangement', '0002_blockedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='support_subdomains',
            field=models.BooleanField(default=False, verbose_name='Support Subdomains'),
        ),
    ]
