# Generated by Django 5.2.7 on 2025-10-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_mangement', '0003_site_support_subdomains'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='dns_challenge_created_at',
            field=models.DateTimeField(blank=True, help_text='When the DNS challenge was generated', null=True, verbose_name='DNS Challenge Created At'),
        ),
        migrations.AddField(
            model_name='site',
            name='dns_challenge_key',
            field=models.CharField(blank=True, help_text='The DNS record name for ACME challenge (e.g., _acme-challenge.example.com)', max_length=255, null=True, verbose_name='DNS Challenge Key'),
        ),
        migrations.AddField(
            model_name='site',
            name='dns_challenge_value',
            field=models.CharField(blank=True, help_text='The TXT record value for ACME challenge', max_length=500, null=True, verbose_name='DNS Challenge Value'),
        ),
    ]
